version: 0.2
env:
  variables:
    PACKAGE: "github.com/kelberg-r/go_app"
phases:
  install:
    runtime-versions:
      golang: 1.15
    commands:
      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}"
  pre_build:
    commands:
      - sudo apt update && sudo apt-get -y install sqlite3
      - cd "/go/src/${PACKAGE}"
      - go get -t ./...
      #- cd $CODEBUILD_SRC_DIR/Tasks
    #  - cat schema.sql | sqlite3 tasks.db
  build:
    commands:
      - go build -o application

artifacts:
   files:
     - application
