version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands: 
    - echo Logging in to Amazon ECR.... 
    - aws --version
    # update the following line with your own region
    - $(aws ecr get-login --no-include-email --region eu-east-1)
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - IMAGE_TAG=${COMMIT_HASH:=latest}
    - REPOSITORY_URI=242307434447.dkr.ecr.us-east-1.amazonaws.com/goapp

