version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.15
    commands:
      - cd "/go/src/${PACKAGE}"
      - go get -t ./...

  pre_build:
    commands:
      #- cd $CODEBUILD_SRC_DIR/Tasks
    #  - cat schema.sql | sqlite3 tasks.db
  build:
    commands:
      - go build -o application

artifacts:
   files:
     - application
