version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.15
    commands:
      - go get github.com/kelberg-r/go_app

  pre_build:
    commands:
      #- cd $CODEBUILD_SRC_DIR/Tasks
    #  - cat schema.sql | sqlite3 tasks.db
  build:
    commands:
      - go build -o app

artifacts:
   files:
     - app
